In [1]:
import pandas as pd
import numpy as np

In [6]:
s = pd.Series([5,20,30,35,60], index=['a','b','c','d','e'])
s

a     5
b    20
c    30
d    35
e    60
dtype: int64

In [7]:
s['c']

np.int64(30)

In [9]:
s[1:4] #b-d

b    20
c    30
d    35
dtype: int64

In [10]:
s['a':'c'] #a - cไม่เหมือนกับ slicing แบบเลข

a     5
b    20
c    30
dtype: int64

In [18]:
df1 = pd.DataFrame(np.random.randint(10, 50, [5,4]),
                   index = ['a','b','c','d','e'],
                  columns = ['w','x','y','z'] )
df1

    w   x   y   z
a  18  47  25  17
b  36  23  36  40
c  20  28  23  34
d  20  44  17  20
e  26  43  32  38

In [24]:
df1 = pd.DataFrame(np.random.randint(10, 50, [5,4]),
                   index = list('abcde'),
                  columns = 'Age Weight Height xyz'.split() )
df1

   Age  Weight  Height  xyz
a   27      18      10   36
b   36      37      28   43
c   14      24      22   28
d   17      43      25   46
e   33      33      23   34

In [23]:
#pandas จะเลือกหลักก่อนแถว

In [25]:
df1.Age

a    27
b    36
c    14
d    17
e    33
Name: Age, dtype: int32

In [31]:
df1.loc['a'] #เข้าจากชื่อ

Age       27
Weight    18
Height    10
xyz       36
Name: a, dtype: int32

In [33]:
df1.iloc[3] #เข้าจากตำแหน่ง

Age       17
Weight    43
Height    25
xyz       46
Name: d, dtype: int32

In [34]:
df1['Weight'] #มองเป็น series

a    18
b    37
c    24
d    43
e    33
Name: Weight, dtype: int32

In [35]:
df1[ ['Weight'] ] #มองเป็น 2 มิติ

   Weight
a      18
b      37
c      24
d      43
e      33

In [36]:
df1.loc[ ['c','d'] ]

   Age  Weight  Height  xyz
c   14      24      22   28
d   17      43      25   46

In [37]:
df1['Age']['c'] #[row][col]

np.int32(14)

In [38]:
df1.loc[ 'a':'c', ['Weight', 'Height']]

   Weight  Height
a      18      10
b      37      28
c      24      22

In [40]:
df = pd.read_csv('Exsample.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [2]:
df = pd.read_csv('Sample - Superstore.csv', encoding='ISO-8859-1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [43]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [72]:
df [df['Sales']>500]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conferenceÿphoneÿ- Charcoal black,911.4240,4,0.20,68.3568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9931,9932,CA-2015-104948,11/13/2015,11/17/2015,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,92404,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960
9942,9943,CA-2014-143371,12/28/2014,1/3/2015,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,92804,West,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.8200,9,0.00,29.9646
9947,9948,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.8800,6,0.00,539.2464
9948,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.2000,8,0.00,793.7160
9968,9969,CA-2017-153871,12/11/2017,12/17/2017,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,7060,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.9800,2,0.00,331.1910

In [71]:
df[ df['City'] == 'Los Angeles' ]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,9977,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.584,2,0.2,31.1980
9977,9978,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.860,7,0.0,0.0000
9978,9979,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.376,4,0.2,4.6816
9979,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152
9986,9987,CA-2016-125794,9/29/2016,10/3/2016,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208

In [81]:
df[ df['Sales'] == df['Sales'].max() ]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.48,6,0.5,-1811.0784

In [94]:
a = df [ df['Sales']>500 ]
a[a['Quantity'] == 1]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
529,530,US-2015-138303,9/3/2015,9/7/2015,Standard Class,MG-18145,Mike Gockenbach,Consumer,United States,Philadelphia,...,19134,East,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,666.248,1,0.2,-149.9058
1549,1550,CA-2014-134278,7/6/2014,7/8/2014,First Class,EP-13915,Emily Phan,Consumer,United States,New York City,...,10011,East,TEC-CO-10001046,Technology,Copiers,Canon Imageclass D680 Copier / Fax,559.992,1,0.2,174.9975
2239,2240,CA-2016-146633,11/15/2016,11/17/2016,Second Class,TG-21310,Toby Gnade,Consumer,United States,Los Angeles,...,90049,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,1016.792,1,0.2,381.2970
5068,5069,CA-2014-124478,8/8/2014,8/12/2014,Standard Class,MA-17560,Matt Abelman,Home Office,United States,Trenton,...,48183,Central,TEC-CO-10001571,Technology,Copiers,Sharp 1540cs Digital Laser Copier,549.990,1,0.0,274.9950
5772,5773,CA-2015-158939,11/26/2015,12/1/2015,Standard Class,EA-14035,Erin Ashbrook,Corporate,United States,Springfield,...,65807,Central,TEC-CO-10002313,Technology,Copiers,Canon PC1080F Personal Copier,599.990,1,0.0,233.9961
5850,5851,CA-2015-121783,11/10/2015,11/14/2015,Standard Class,PO-19180,Philisse Overcash,Home Office,United States,Roseville,...,55113,Central,TEC-CO-10001571,Technology,Copiers,Sharp 1540cs Digital Laser Copier,549.990,1,0.0,274.9950
6363,6364,CA-2017-110443,11/21/2017,11/25/2017,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Renton,...,98059,West,TEC-MA-10002073,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, White",1039.992,1,0.2,103.9992
7685,7686,CA-2015-116876,2/14/2015,2/21/2015,Standard Class,TT-21070,Ted Trevino,Consumer,United States,Rochester,...,14609,East,TEC-PH-10002584,Technology,Phones,Samsung Galaxy S4,625.990,1,0.0,187.7970
7927,7928,CA-2017-120404,11/20/2017,11/24/2017,Second Class,KH-16330,Katharine Harms,Corporate,United States,New York City,...,10035,East,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,569.990,1,0.0,170.9970
8760,8761,CA-2016-159891,1/31/2016,2/6/2016,Standard Class,BF-11170,Ben Ferrer,Home Office,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,1270.990,1,0.0,635.4950
9734,9735,CA-2014-114321,8/20/2014,8/25/2014,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,...,23666,South,OFF-BI-10001359,Office Supplies,Binders,GBC DocuBind TL300 Electric Binding System,896.990,1,0.0,421.5853

In [95]:
df[ (df['Sales']>500) & (df['Quantity']==1)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
529,530,US-2015-138303,9/3/2015,9/7/2015,Standard Class,MG-18145,Mike Gockenbach,Consumer,United States,Philadelphia,...,19134,East,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,666.248,1,0.2,-149.9058
1549,1550,CA-2014-134278,7/6/2014,7/8/2014,First Class,EP-13915,Emily Phan,Consumer,United States,New York City,...,10011,East,TEC-CO-10001046,Technology,Copiers,Canon Imageclass D680 Copier / Fax,559.992,1,0.2,174.9975
2239,2240,CA-2016-146633,11/15/2016,11/17/2016,Second Class,TG-21310,Toby Gnade,Consumer,United States,Los Angeles,...,90049,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,1016.792,1,0.2,381.2970
5068,5069,CA-2014-124478,8/8/2014,8/12/2014,Standard Class,MA-17560,Matt Abelman,Home Office,United States,Trenton,...,48183,Central,TEC-CO-10001571,Technology,Copiers,Sharp 1540cs Digital Laser Copier,549.990,1,0.0,274.9950
5772,5773,CA-2015-158939,11/26/2015,12/1/2015,Standard Class,EA-14035,Erin Ashbrook,Corporate,United States,Springfield,...,65807,Central,TEC-CO-10002313,Technology,Copiers,Canon PC1080F Personal Copier,599.990,1,0.0,233.9961
5850,5851,CA-2015-121783,11/10/2015,11/14/2015,Standard Class,PO-19180,Philisse Overcash,Home Office,United States,Roseville,...,55113,Central,TEC-CO-10001571,Technology,Copiers,Sharp 1540cs Digital Laser Copier,549.990,1,0.0,274.9950
6363,6364,CA-2017-110443,11/21/2017,11/25/2017,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Renton,...,98059,West,TEC-MA-10002073,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, White",1039.992,1,0.2,103.9992
7685,7686,CA-2015-116876,2/14/2015,2/21/2015,Standard Class,TT-21070,Ted Trevino,Consumer,United States,Rochester,...,14609,East,TEC-PH-10002584,Technology,Phones,Samsung Galaxy S4,625.990,1,0.0,187.7970
7927,7928,CA-2017-120404,11/20/2017,11/24/2017,Second Class,KH-16330,Katharine Harms,Corporate,United States,New York City,...,10035,East,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,569.990,1,0.0,170.9970
8760,8761,CA-2016-159891,1/31/2016,2/6/2016,Standard Class,BF-11170,Ben Ferrer,Home Office,United States,Atlanta,...,30318,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,1270.990,1,0.0,635.4950
9734,9735,CA-2014-114321,8/20/2014,8/25/2014,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,...,23666,South,OFF-BI-10001359,Office Supplies,Binders,GBC DocuBind TL300 Electric Binding System,896.990,1,0.0,421.5853

In [97]:
df['Ship Mode'].unique() #หาว่ามีอะไรมั่ง

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [98]:
df['Ship Mode'].nunique() #หาว่า shipmode มีกี่ เหมือนกับ len(df['Ship Mode'].unique())

4

In [99]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [100]:
df['Sales'].sum()

np.float64(2297200.8603000003)

In [105]:
#อยากหายอดขายรวมแต่ละ region
df.groupby('Region')['Sales'].describe()

,count,mean,std,min,25%,50%,75%,max
Region,,,,,,,,
Central,2323.0,215.772661,632.779010,0.444,14.620,45.980,200.0120,17499.950
East,2848.0,238.336110,620.712652,0.852,17.520,54.900,209.6175,11199.968
South,1620.0,241.803645,774.796273,1.167,17.187,54.594,208.7220,22638.480
West,3203.0,226.493233,524.876877,0.990,19.440,60.840,215.8090,13999.960

In [109]:
df.groupby(['Region','Category'])['Sales'].sum()

Region   Category
Central  Furniture          163797.1638
         Office Supplies    167026.4150
         Technology         170416.3120
East     Furniture          208291.2040
         Office Supplies    205516.0550
         Technology         264973.9810
South    Furniture          117298.6840
         Office Supplies    125651.3130
         Technology         148771.9080
West     Furniture          252612.7435
         Office Supplies    220853.2490
         Technology         251991.8320
Name: Sales, dtype: float64

In [113]:
df.groupby('Ship Mode')['Sales'].count().sort_values()

Ship Mode
Same Day           543
First Class       1538
Second Class      1945
Standard Class    5968
Name: Sales, dtype: int64

In [111]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [114]:
def fn(x):
    return x**2

In [115]:
df['Sales'].apply(fn) #apply จะไม่เปลี่ยนค่าต้นทาง

0        68623.041600
1       535736.163600
2          213.744400
3       916954.668506
4          500.327424
            ...
9989       637.461504
9990      8456.641600
9991     66861.547776
9992       876.160000
9993     59126.785600
Name: Sales, Length: 9994, dtype: float64

In [197]:
def findWord(s):
    return 'collection' in s.lower()

In [198]:
df[df['Product Name'].apply(findWord)]['Product Name'].value_counts()

Product Name
DMI Arturo Collection Mission-style Design Wood Chair                                 11
Bush Westfield Collection Bookcases, Medium Cherry Finish                              9
Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table         9
Lesro Round Back Collection Coffee Table, End Table                                    8
Bush Heritage Pine Collection 5-Shelf Bookcase, Albany Pine Finish, *Special Order     8
Bush Advantage Collection Racetrack Conference Table                                   7
Sauder Camden County Collection Libraries, Planked Cherry Finish                       7
Bush Westfield Collection Bookcases, Fully Assembled                                   6
Flexible Leather- Look Classic Collection Ring Binder                                  6
Regeneration Desk Collection                                                           5
Rush Hierlooms Collection 1" Thick Stackable Bookcases                                 4
Bush Advantage Collection Round Conference Table                                       4
Bush Somerset Collection Bookcase                                                      4
Conquest 14 Commercial Heavy-Duty Upright Vacuum, Collection System, Accessory Kit     4
Sauder Facets Collection Library, Sky Alder Finish                                     4
Bush Cubix Collection Bookcases, Fully Assembled                                       3
Sauder Cornerstone Collection Library                                                  3
Bush Westfield Collection Bookcases, Dark Cherry Finish                                3
Southworth Structures Collection                                                       2
Sauder Facets Collection Locker/File Cabinet, Sky Alder Finish                         2
Sauder Camden County Collection Library                                                2
Eldon Expressions Mahogany Wood Desk Collection                                        2
Rush Hierlooms Collection Rich Wood Bookcases                                          2
Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order              1
Bush Birmingham Collection Bookcase, Dark Cherry                                       1
Bush Westfield Collection Bookcases, Dark Cherry Finish, Fully Assembled               1
Name: count, dtype: int64

In [201]:
a = df[ df['Product Name'].apply(findWord) ]
b = a['Product Name'].value_counts()
lst = b[b == 4]
for x in lst.index:
    display(df[df['Product Name']==x])

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3351,3352,US-2014-134733,9/23/2014,9/28/2014,Standard Class,BM-11650,Brian Moss,Corporate,United States,San Diego,...,92037,West,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",435.999,3,0.15,20.5176
3994,3995,CA-2015-105627,3/8/2015,3/12/2015,Standard Class,DK-12895,Dana Kaydos,Consumer,United States,Kenosha,...,53142,Central,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",512.940,3,0.00,97.4586
5161,5162,CA-2014-111192,7/30/2014,8/5/2014,Standard Class,TS-21430,Tom Stivers,Corporate,United States,Seattle,...,98103,West,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",1367.840,8,0.00,259.8896
7671,7672,CA-2015-130974,11/27/2015,11/29/2015,Second Class,MA-17560,Matt Abelman,Home Office,United States,Everett,...,2149,East,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",170.980,1,0.00,32.4862

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
231,232,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,233.86,2,0.45,-102.048
3710,3711,CA-2017-113670,10/15/2017,10/17/2017,First Class,RS-19765,Roland Schwarz,Corporate,United States,Los Angeles,...,90045,West,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,510.24,3,0.20,6.378
5075,5076,CA-2014-134572,4/20/2014,4/22/2014,Second Class,SV-20365,Seth Vernon,Consumer,United States,Houston,...,77070,Central,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,744.10,5,0.30,-95.670
6881,6882,CA-2015-137113,12/1/2015,12/5/2015,Second Class,TW-21025,Tamara Willingham,Home Office,United States,Seattle,...,98105,West,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,1913.40,9,0.00,401.814

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.00,41.9136
5399,5400,CA-2016-117681,4/9/2016,4/14/2016,Standard Class,HF-14995,Herbert Flentye,Consumer,United States,Los Angeles,...,90004,West,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,556.665,5,0.15,6.5490
8634,8635,CA-2017-159793,8/25/2017,8/29/2017,Standard Class,SV-20365,Seth Vernon,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,130.980,2,0.50,-89.0664
9334,9335,CA-2017-110198,5/1/2017,5/2/2017,First Class,AG-10900,Arthur Gainer,Consumer,United States,Coral Springs,...,33065,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,314.352,3,0.20,-15.7176

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1578,1579,CA-2016-102456,2/27/2016,3/1/2016,First Class,DL-12865,Dan Lawera,Consumer,United States,New York City,...,10011,East,OFF-AP-10004336,Office Supplies,Appliances,Conquest 14 Commercial Heavy-Duty Upright Vacu...,170.880,3,0.0,49.5552
3051,3052,US-2017-148054,10/6/2017,10/11/2017,Standard Class,NZ-18565,Nick Zandusky,Home Office,United States,Meridian,...,83642,West,OFF-AP-10004336,Office Supplies,Appliances,Conquest 14 Commercial Heavy-Duty Upright Vacu...,227.840,4,0.0,66.0736
3708,3709,CA-2014-120544,11/23/2014,11/27/2014,Standard Class,SS-20140,Saphhira Shifley,Corporate,United States,Mesquite,...,75150,Central,OFF-AP-10004336,Office Supplies,Appliances,Conquest 14 Commercial Heavy-Duty Upright Vacu...,34.176,3,0.8,-87.1488
6661,6662,CA-2015-129322,8/8/2015,8/10/2015,Second Class,DB-13405,Denny Blanton,Consumer,United States,Lawrence,...,1841,East,OFF-AP-10004336,Office Supplies,Appliances,Conquest 14 Commercial Heavy-Duty Upright Vacu...,113.920,2,0.0,33.0368

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1723,1724,US-2015-123218,12/20/2015,12/25/2015,Standard Class,KD-16345,Katherine Ducich,Consumer,United States,Chicago,...,60623,Central,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",359.058,3,0.30,-71.8116
3365,3366,CA-2014-115161,1/31/2014,2/2/2014,First Class,LC-17050,Liz Carlisle,Consumer,United States,Mission Viejo,...,92691,West,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",290.666,2,0.15,3.4196
8038,8039,CA-2017-109393,6/30/2017,7/2/2017,Second Class,JC-15775,John Castell,Consumer,United States,Los Angeles,...,90032,West,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",435.999,3,0.15,5.1294
8802,8803,CA-2016-140935,11/10/2016,11/12/2016,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,73120,Central,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.00,54.7136

In [6]:
# แปลงเป็น format date
df['Ship Year'] = (pd.to_datetime(df['Ship Date'], format = '%m/%d/%Y')).apply(lambda x : x.year)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship Year
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2017
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2017
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2017

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480